### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by coldfix** [marcus-oscarsson/pyqtconsole#13]
Hi, do you want to release this project under a certain license?

If license unspecified it technically means that you reserve all rights and no one can safely use it.

If you're not already well-informed about licenses I recommend one of:

- GPLv3+/LGPL: anyone can use it for anything, but anything it's included in must be free (GPL-compatible) software
- MIT/BSD: free, but retain copyright notice in the source code
- Unlicense: simple, basically public domain

**Comment by marcus-oscarsson** [comment]
Hey

Thanks for the heads up. I did not have any particular license in mind I usually work with GPL or MIT. MIT would be fine, ill try to get some time to add a license and upload a new version to PYPI as well.

Thanks for all the input :)
Marcus

**Comment by marcus-oscarsson** [comment]
@coldfix 

Thanks for taking a look the project and submitting the PR's, I have uploaded a new version 1.1.1 to PyPI. I will follow semantic versioning from now on :)

**Comment by marcus-oscarsson** [comment]
Its now licensed under MIT
