### ISSUE TITLE
How can I change the theme of this pyqtconsole

### ISSUE THREAD

**Issue by akverma26** [marcus-oscarsson/pyqtconsole#21]

**Comment by marcus-oscarsson** [comment]
Not sure exactly what you mean by theme, it should use the system theme as any Qt application

**Comment by akverma26** [comment]
Actually, I want to change the color of the text according to me. How can I do the same?

**Comment by marcus-oscarsson** [comment]
I see, we currently don't have any support for customizing the syntax highlighter if that's what you would like to do ?
