### ISSUE TITLE
AttributeError: type object 'ConnectionType' has no attribute 'QueuedConnection'

### ISSUE THREAD

**Issue by anubhavkamath** [marcus-oscarsson/pyqtconsole#23]
I get this error when trying to use pyqtconsole. The console does show up if I remove the eval_queued call which is where the problem is.

    app = QApplication(sys.argv)
    console = PythonConsole()
    console.show()
    console.eval_queued()

**Comment by The-Compiler** [comment]
What PyQt version are you using? Looks like pyqtconsole uses scoped enum access (`Qt.ConnectionType.QueuedConnection`) which was added in PyQt 5.11 (IIRC).

**Comment by anubhavkamath** [comment]
That was it. I was using 5.9.2. I upgraded to 5.11 and it works now. Thanks.

**Comment by marcus-oscarsson** [comment]
Prefect thanks @The-Compiler for the quick answer !

**Comment by The-Compiler** [comment]
@marcus-oscarsson Given that pyqtconsole even supports PyQt 4 (which is long dead...), is it intended that it doesn't support PyQt 5.9 (Qt 5.9 is still supported as an LTS)?

**Comment by marcus-oscarsson** [comment]
@The-Compiler No its not really intended. I have not taken any active decision regarding Qt4 although the idea was to keep the compatibility as long as possible. I have very little time to keep maintaining the project so keeping both Qt4 and Qt5 support will be complicated.

It should support Qt 5.9, that it does not is a bug, I unfortunately don't really have time to fix it for the moment. Contributions are very welcome :)

Cheers,
Marcus

**Comment by The-Compiler** [comment]
FWIW for this specific case, you can just use `Qt.QueuedConnection` instead of `Qt.ConnectionType.QueuedConnection` - that'll continue to work until PyQt6.

Not sure if there are any other enums though, and I currently have a lot on my plate as well :wink:

**Comment by marcus-oscarsson** [comment]
@The-Compiler oh, thanks that's really good to know ill try to see what I can do :). Just by curiosity how do you know that it will remain for PyQt6 as well  ?

... Busy days I guess :)

**Comment by The-Compiler** [comment]
It will stop working with PyQt6, see https://www.riverbankcomputing.com/static/Docs/PyQt5/gotchas.html#enums

> With SIP v4.19.9 members of traditional C/C++ enums are now also visible within the scope of the enum. It is strongly recommended that enum members are always referenced by specifying the scope of the enum. PyQt6 will not allow any other method of access.

For my project I'll keep the old non-namespaced access until PyQt6 and then probably introduce a helper function which tries both (to continue working with older PyQt versions) or maybe drop support for Qt 5.9/5.10 at that point.

**Comment by marcus-oscarsson** [comment]
@The-Compiler thanks again for the info, sounds like a good idea !

**Comment by marcus-oscarsson** [comment]
@anubhavkamath so there is a fix made by @coldfix that solves your issue without the need to update PyQt
