### ISSUE TITLE
No module named '__builtin__'

### ISSUE THREAD

**Issue by shahram10715** [marcus-oscarsson/pyqtconsole#26]
while I was trying to run on debian 10 the simple example which has been provided in pypi I encountered the following error:

    
    File "/home/sh/spyder/temp.py", line 5, in <module>
      from pyqtconsole.console import PythonConsole
    File "/home/sh/anaconda3/lib/python3.7/site-packages/pyqtconsole/console.py", line 10, in  <module>
    from .interpreter import PythonInterpreter
    File "/home/sh/anaconda3/lib/python3.7/site-packages/pyqtconsole/interpreter.py", line 14, in <module>
    from __builtin__ import exit    # py2
    ModuleNotFoundError: No module named '__builtin__'

then I search for solution like changing to:  __ builtins __,  __ builtin __, __ builtin __ . __  dict __
but still have the same problem.

**Comment by The-Compiler** [comment]
The code behind it:

```python
try:
    from builtins import exit       # py3
except ImportError:
    from __builtin__ import exit    # py2
```

I'm not sure why that wouldn't work. What happens if you run `python3 -c "from builtins import exit"`? What about `python3 -c "import builtins; print(builtins.__file__)"`?

**Comment by shahram10715** [comment]
first of all I have to mention that I'm using python37. The first command you mentioned works fine. but the second one returns the following error:


    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    AttributeError: module 'builtins' has no attribute '__file__'


by the way, I could easily run it on windows 10.

**Comment by shahram10715** [comment]
This is the webpage I was trying to find something useful:
https://www.programcreek.com/python/example/2117/code.InteractiveConsole

**Comment by The-Compiler** [comment]
If `python3 -c "from builtins import exit"` works, you should never get to the line trying to import from `__builtin__`. Are you sure you're using the same Python for both? From your stacktrace above, you seem to be using Anaconda's Python.

**Comment by shahram10715** [comment]
yes I'm trying it with spyder. but the two code snippets you sent, I tried them on my ordinary terminal.
Again when I'm trying the code out of spyder (in terminal) I see the following message:


    Traceback (most recent call last):
    File "./n1.py", line 10, in <module>
    console.eval_in_thread()
    File "/home/sh/anaconda3/lib/python3.7/site-packages/pyqtconsole/console.py", line 582, in eval_in_thread
    self.interpreter.exec_, Qt.ConnectionType.QueuedConnection)
AttributeError: type object 'ConnectionType' has no attribute 'QueuedConnection'

**Comment by coldfix** [comment]
The last traceback appears to be the same issue as reported in #23 that appears for PyQt5<5.11. It has been fixed on master but not yet released.

However, this doesn't really explain the first traceback you showed. Can you reproduce and describe the exact circumstances under which you obtain the initially reported error?

**Comment by shahram10715** [comment]
yes I can definitely reproduce that error. As I mentioned earlier I am using Debian 10, and im trying to run the code on Spyder IDE, and I have python3.7. if you need any extra information which I didn't provide ask to me to give more information about my machine and system. my first comment is not the complete error message, so I post it again here:


    runfile('/home/sh/spyder/temp03.py', wdir='/home/sh/spyder')
    Traceback (most recent call last):
    File "<ipython-input-3-d0dc2c800490>", line 1, in <module>
    runfile('/home/sh/spyder/temp03.py', wdir='/home/sh/spyder')
    File "/home/sh/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)
    File "/home/sh/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
    File "/home/sh/spyder/temp03.py", line 5, in <module>
    from pyqtconsole.console import PythonConsole
    File "/home/sh/anaconda3/lib/python3.7/site-packages/pyqtconsole/console.py", line 10, in <module>
    from .interpreter import PythonInterpreter
    File "/home/sh/anaconda3/lib/python3.7/site-packages/pyqtconsole/interpreter.py", line 14, in <module>
    from __builtin__ import exit    # py2
    ModuleNotFoundError: No module named '__builtin__'

**Comment by coldfix** [comment]
Hey, thanks for the info.

I installed spyder and can reproduce. It seems that spyder deletes `exit` from the builtins:

```python
>>> import builtins
>>> print('exit' in dir(builtins))
False
```

Not sure why they are doing this, probably so that it doesn't conflict with their custom exit.

Normally, I would consider this a misfeature of spyder that doesn't warrant a fix here, but it should be easy enough to do by simply defining a custom `exit` function that just raises `SystemExit` instead of importing it. I can do the patch/PR later or tomorrow.
