### ISSUE TITLE
User-specified colors

### ISSUE THREAD

**Issue by jacobwilliams** [marcus-oscarsson/pyqtconsole#29]
For my application, it would be nice to be able to change the colors used for syntax highlighting. I think it might just require `STYLES` to be an optional user input. I can try to work on that.

**Comment by marcus-oscarsson** [comment]
@jacobwilliams sure that would be a welcome contribution, I have no time to work on it myself.

**Comment by coldfix** [comment]
Hi @jacobwilliams ,

I added a corresponding argument to forward format settings to the highlighter. This will be in the next release. Note that I would consider the API provisional for now, i.e. the API might change if we find a better name or easier syntax. In this case, we will of course ping here.

Let us know what you think.

Best, Thomas
