### ISSUE TITLE
Completion cuts text incorrectly

### ISSUE THREAD

**Issue by The-Compiler** [marcus-oscarsson/pyqtconsole#3]
With `inuithread.py` with the 3rdparty-reports removed, it seems the completion doesn't work properly with jedi.

When I do `import sys`, and type `sys.<tab><enter>` to select `sys.abiflags`, I get `sys.lags`. When I do `sys.e<tab><enter>` to select `sys.exc_info`, I get `sys.enfo`.

This is with PyQt 5.3.2 and Python 3.4.

**Comment by marcus-oscarsson** [comment]
I fixed this problem a while ago and I can't seem to be able to reproduce it now. I might of course have missed something, but could you try to pull the latest version, and see if you can reproduce this. 

Thanks !
