### ISSUE TITLE
More than one continuation line

### ISSUE THREAD

**Issue by jacobwilliams** [marcus-oscarsson/pyqtconsole#30]
The logic for multiline code seems to only work for two lines.  Example:

![image](https://user-images.githubusercontent.com/6483379/69280242-90826800-0bab-11ea-9de9-05977197e9b1.png)

A regular python console would continue to expect additional indented lines until you enter a blank line:

![image](https://user-images.githubusercontent.com/6483379/69280328-c0ca0680-0bab-11ea-916a-82f1f7785b37.png)

This would be nice to have.

**Comment by coldfix** [comment]
Hi,

thanks for reporting. It is intended to work like a regular python console as you expected as well. This appears to be a regression due to a recent change I made (see 6b47dfd). I am working on a fix.

Best, Thomas

**Comment by marcus-oscarsson** [comment]
@coldfix thanks for taking a look at this and @jacobwilliams thanks for reporting

**Comment by jacobwilliams** [comment]
Thanks!! Do you think you can publish this to PyPi also?

**Comment by coldfix** [comment]
@jacobwilliams It is now released on PyPI.
