### ISSUE TITLE
Continued lines are indented wrong

### ISSUE THREAD

**Issue by The-Compiler** [marcus-oscarsson/pyqtconsole#4]
When the prompt number is a single digit, there's a missing space after the second `:` which makes it hard to line up the code:

```
IN [0]: while True:
   ...:test
```

When it's two digits, it looks like this instead, i.e. there's also a missing space before `...`:

```
IN [16]: while True:
   ...:test
```

**Comment by marcus-oscarsson** [comment]
Fixed, please let me know if it solves your problem
