### ISSUE TITLE
Use pyqtconsole to interact with Qt Mainwindows

### ISSUE THREAD

**Issue by MattiaMartinelli** [marcus-oscarsson/pyqtconsole#47]
Good morning,
I'm new with PyQt so sorry if this question is too simple.
I'm creating a PyQt main window with the pyvista library in order to upload, visualize and create 3D meshes,
I would like to insert in the Main window or in another small window a Python console that is able to interact with the main window.
Is it possible to do that with pyqtconsole?

thank you

Mattia

**Comment by coldfix** [comment]
Hi,

sure this is possible. Just create the widget as shown in the examples and insert it into your widget layout as you would with other subwidgets. You can expose variables via the `push_local_ns()` method or directly by manipulating `console.interpreter.locals`.

Best, Thomas
