### ISSUE TITLE
Magic IPython functions not accesible through pyqtconsole

### ISSUE THREAD

**Issue by eccortes95** [marcus-oscarsson/pyqtconsole#48]
Hi, 
I would like to know if the magic functions (as in iPython) will be at some point available through the pyqtconsole. 
E.g. %ls, %cd.
Cheers, 
Cris Cortes

**Comment by coldfix** [comment]
pyqtconsole was created as a more lightweight alternative to ipython/jupyter and is intentionally not using ipython under the hood. If someone were to implement similar functionality for some of these commands in a clean and lightweight fashion, I personally wouldn't object.
