### ISSUE TITLE
Console allows clicking anywhere

### ISSUE THREAD

**Issue by The-Compiler** [marcus-oscarsson/pyqtconsole#5]
The user can click anywhere to move the cursor to that position and enter text, which makes for a very confusing output.

In my console widget, I solved this by having a read-only `QTextEdit` for the output, and a separate `QLineEdit` for the input.

**Comment by marcus-oscarsson** [comment]
Ah, yes that is quite annoying. Having a separate QLineEdit is of course a solution as well. Should be fixed now, let me know how it works
