### ISSUE TITLE
Unable to type square brackets [ ] and others in French Layout Windows 10

### ISSUE THREAD

**Issue by byteptr** [marcus-oscarsson/pyqtconsole#53]
Hello, 
I'm using Python 3.7.4 and pyqtconsole 1.1.5 on Windows 10 machine. I can't type any of the characters that needs Alt-Gr key on AZERTY French layout keyboard. Please, see image below
![image](https://user-images.githubusercontent.com/35638772/77850134-c1fde680-71d0-11ea-8b3c-c9cbc294f9c5.png)
I think the event loop is capturing these keys and filtering. How can I overcome this problem? 
Thanks in advance

**Comment by byteptr** [comment]
> Hello,
> I'm using Python 3.7.4 and pyqtconsole 1.1.5 on Windows 10 machine. I can't type any of the characters that needs Alt-Gr key on AZERTY French layout keyboard. Please, see image below
> ![image](https://user-images.githubusercontent.com/35638772/77850134-c1fde680-71d0-11ea-8b3c-c9cbc294f9c5.png)
> I think the event loop is capturing these keys and filtering. How can I overcome this problem?
> Thanks in advance

Hi, I tested a standalone PyQT application without pyqtconsole capturing the keys overriding keyPressEvent() method, and I have verified that QT incorrectly assignes AltGr to Alt key, this agrees with this bug report https://bugreports.qt.io/browse/QTBUG-69317
I'm wondering if It is possible to fix this issue independently capturing the keys first with another library and then sending tho console's buffer.... I know this is not very fancy, but it does it independent of third party bugs as something provisional

**Comment by byteptr** [comment]
Hi again, 
I dig into your code and I got console working, I fixed the issue modifiying console.py _filter_keyPressEvent() method defined at line 184. Qt 5.9.2 takes AltGr as Ctrl+Alt shortcut so I modified the logical condition, please take a look below (sorry I didn't clone yet the project): 

Original code: 
![image](https://user-images.githubusercontent.com/35638772/77854044-13fe3680-71e8-11ea-8ff8-f48a5a9ba2f2.png)

Fixed code: 
![image](https://user-images.githubusercontent.com/35638772/77854052-211b2580-71e8-11ea-8b5e-2e43e523b3bd.png)

Now I have Python console full working: 
![image](https://user-images.githubusercontent.com/35638772/77854080-53c51e00-71e8-11ea-8ab4-5e4e38c44ba6.png)

The point is: There is a better and cleaner way to do this ?

Thanks

**Comment by coldfix** [comment]
Hi,

good catch! I think in principle that's the way to fix it.

Maybe we should at some point use an abstraction layer that translates key bindings to handlers.

**Comment by coldfix** [comment]
(by the way: on my keyboard AltGr works as expected, weird..)

**Comment by byteptr** [comment]
Hi, thank you for you fast reply. I'd like to test under Linux also but I have some problems updating packages (none of them related to qtconsole). As it says on bugreports I'm almost sure (99%) that it's Win10 and Qt 5.9.2 combined problem...
