### ISSUE TITLE
Exception starts on same line when a continued line is entered

### ISSUE THREAD

**Issue by The-Compiler** [marcus-oscarsson/pyqtconsole#6]
Last one for now, I promise :wink:

```
IN [30]: while True:
   ...:bla  File "<console>", line 2
    bla
      ^
IndentationError: expected an indented block
```

The `File ...` should probably start on the next line, like with "regular" input causing exceptions.

**Comment by marcus-oscarsson** [comment]
Thanks for your feedback its great that you take time send me this information. I haven't had time to fix the problems yet, but I will take a look as soon as I can :)

Cheers !

**Comment by marcus-oscarsson** [comment]
By they way, which version/commit are you using ?

**Comment by The-Compiler** [comment]
I think I was using the 1.0 release - sorry for not mentioning that!
