### ISSUE TITLE
object has no attribute 'eval_in_thread'

### ISSUE THREAD

**Issue by seghier** [marcus-oscarsson/pyqtconsole#8]
hi ; i have this problem ; i use python 3.5 / PyQt5 / windows 10 64bits
 console.eval_in_thread()
AttributeError: 'PythonConsole' object has no attribute 'eval_in_thread'

**Comment by seghier** [comment]
it work now but i don't understand how i can use the window ?
if for example i have an application and i want when i click a button to run a script this console appear like windows console and show messages and what the script do .
can pyqtconsole do that ?

**Comment by marcus-oscarsson** [comment]
Hi @seghier 

I'm not entirely sure that i understand what you'd like to do, its sounds to me that
you'd just like to have the output of stdout and stderr. Would you also like the user to
be able to execute commands from this window ? If yes sure you can use it, like that.

If not id simply suggest to pipe the stdout or and stderr to the process you'd like to 
"watch".

Cheers,
Marcus

**Comment by seghier** [comment]
thank you and sorry .
i create an application and when i run the script the cmd window (of windows) appear .
i ask if it is possible to use your script to show the cmd window inside my app ; i search in google but i don't find clear answer or examlpes.

**Comment by marcus-oscarsson** [comment]
Okey, I hope that you found the answer to your problem. Ill close this issue for now. Don't hesitate to open another one if you have encounter another issue.
